branches:
  only:
  - master
  - develop

install:
  - npm install
  - npm run prepare

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
