image: Previous Visual Studio 2017

branches:
  only:
  - master
  - develop

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Configure so can use  git push (locally) in tests
  - git config --global "user.email" "noreply@no.reply"
  - git config --global "user.name" "Unit Test"
  # run tests
  - npm test

# Don't actually build. (Per example, and do not want default MSBuild.)
build: off
