branches:
  only:
  - master
  - develop

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run prepare
  - npm link

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build: off
