language: node_js
node_js:
  - "node"
before_script:
  - "npm install --global jasmine"
  - npm link
os:
  - linux
  - osx
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
