name: Node CI

on: [push]

jobs:
  # Somewhat unexpectedly, can test Windows and Ubuntu together!
  test-windows:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: git config user.email
      run: git config --global "user.email" "noreply@no.reply"
    - name: git config user.name
      run: git config --global "user.name" "Unit Test"
    - name: npm install
      run: npm ci
    - name: test
      run: npm run test
      env:
        CI: true
  macOS does not have Mercurial preinstalled
  test-macos:
    name: Test on node ${{ matrix.node-version }} and macOS
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: |
        git config --global "user.email" "noreply@no.reply"
        git config --global "user.name" "Unit Test"
        brew install mercurial
        npm install
        npm test
      env:
        CI: true
